### ISSUE TITLE
Issue with Installing

### ISSUE THREAD

**Issue by steady-mongoose** [SumoLogic/sumologictoolbox#10]
When I attempt to install the toolbox, I get this error.

✘ Locking Failed!
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /Users/jmcmullin/.local/share/virtualenvs/sumologictoolbox-KrGG4G3y/bin/python /Library/Python/3.8/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpbksnuxuk
     cwd: /private/tmp/pip-resolver-ev0wv7dm/pyqt5
Complete output (31 lines):
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py", line 103, in prepare_metadata_for_build_wheel
    hook = backend.prepare_metadata_for_build_wheel
AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

**Comment by voltaire321** [comment]
This appears to be an incompatibility with between the latest version of pipenv and older versions of pip. 

To resolve try upgrading pip:

python3 -m pip install --upgrade pip
